= Preface

== Purpose

This document defines the S2 INTG component Data Staging Model.

The intended audience includes implementers, integrators and health data managers.

== Related Documents

Prerequisite documents for reading this document include:

* The {s2_rm_overview}[S2 Architecture Overview^];

== Status

This specification is in the {spec_status} state. The development version of this document can be found at {s2_base_latest_data_types}[{s2_base_latest_data_types}^].

Known omissions or questions are indicated in the text with a 'to be determined' paragraph, as follows:
[.tbd]
*TBD*: (example To Be Determined paragraph)

=== Prior Art

This specification draws from the {openehr_rm_data_types}[openEHR Data Types^] specification and the {hl7_fhir_data_types}[HL7 FHIR Data Types^].

== Feedback

Feedback may be provided on the {s2_specifications_forum}[{product_name} forum^].

Issues may be raised on the {component_prs}[specifications Problem Report tracker^].

To see changes made due to previously reported issues, see the {component_history}[{component} component Change Request tracker^].

== Conformance

Conformance of a data or software artifact to an {product_name} specification is determined by a formal test of that artifact against the relevant {product_name} Implementation Technology Specification(s) (ITSs), such as a JSON-schema or OpenAPI specification. Since ITSs are formal derivations from underlying models, ITS conformance indicates model conformance.

