=== Entity Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*__Entity (abstract)__*

h|*Description*
2+a|Continuant Entity whose identity is stable over its period of existence. Includes physical entities as well as other kinds of entities from the social, legal and business worlds, including intentional agents.

h|*Inherit*
2+|`Locatable`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*description*: `List<link:/releases/RM/{rm_release}/data_structures.html#_item_class[Item^]>`
a|Archetypable generic description for this entity.

h|*0..1*
|*type_uri*: `Uri`
a|URI to a detailed description of the concrete type of Entity represented by instances of any descendant of this class. For example, a specific archetype of `PERSON` might be used to represent Employees. This field might then contain a URI pointing to the relevant description of 'employee' within the owning organisation.

h|*0..1*
|*relationships*: `List<<<_relationship_group_class,Relationship_group>>>`
a|
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*type* (): `Coded_term`
a|Concrete type of entity, such as  `PERSON`,  `ORGANISATION`, etc. Role name, e.g.  general practitioner ,  nurse ,  private citizen . Taken from inherited `_name_` attribute.
|===
