=== Care_entry Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*__Care_entry (abstract)__*

h|*Description*
2+a|The abstract parent of all clinical `Entry` subtypes. A `Care_entry` defines protocol and guideline attributes for all clinical Entry subtypes.

h|*Inherit*
2+|`<<_entry_class,Entry>>`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*method*: `link:/releases/GCM/{gcm_release}/data_structures.html#_cluster_class[Cluster^]`
a|Description of the method (i.e. how) the information in this entry was arrived at. For Observations, this is a description of the method or instrument used. For Assertion, how the evaluation was arrived at. For Orders, how to execute. This may take the form of references to guidelines, including manually followed and executable; knowledge references such as a paper in Medline; clinical reasons within a larger care process.

h|*0..1*
|*guideline_id*: `link:/releases/BASE/{base_release}/foundation_types.html#_uri_class[Uri^]`
a|Optional external identifier of guideline creating this Entry if relevant.

TODO: probably should be a Uri
|===
