=== DvQuantified Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*__DvQuantified (abstract)__*

h|*Description*
2+a|Abstract class defining the concept of relative quantified  'amounts'. For relative quantities, the  `+` and  `-` operators are defined (unlike descendants of `DV_ABSOLUTE_QUANTITY`, such as the date/time types).

h|*Inherit*
2+|`<<_dvordered_class,DvOrdered>>`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*magnitude*: `<<_ordered_numeric_class,Ordered_numeric>>`
a|
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*valid_percentage* ( +
number: `Ordered_Numeric[1]` +
): `Boolean`
a|Test whether a number is a valid percentage, i.e. between 0 and 100.

h|*1..1*
|*add* __alias__ "+" ( +
other: `<<_dvquantified_class,DvQuantified>>[1]` +
): `<<_dvquantified_class,DvQuantified>>` +
 +
__Pre_comparable__: `is_strictly_comparable_to (other)`
a|Sum of this amount and another. The value of accuracy in the result is either:

* the sum of the accuracies of the operands, if both present, or;
* both operand accuracies are unknown_accuracy_value.

If the accuracy value is a percentage in one operand and not in the other, the form in the result is that of the larger operand.

h|*1..1*
|*subtract* __alias__ "-" ( +
other: `<<_dvquantified_class,DvQuantified>>[1]` +
): `<<_dvquantified_class,DvQuantified>>` +
 +
__Pre_comparable__: `is_strictly_comparable_to (other)`
a|Difference of this amount and another. The value of `_accuracy_` in the result is either:

* the sum of the accuracies of the operands, if both present, or;
* unknown, if either or both operand accuracies are unknown.

If the `_accuracy_` value is a percentage in one operand and not in the other, the form in the result is that of the larger operand.

h|*1..1 +
(effected)*
|*is_equal* ( +
other: `<<_dvquantified_class,DvQuantified>>[1]` +
): `Boolean`
a|Return True if this `DV_AMOUNT` is considered equal to `_other_`.

h|*1..1*
|*multiply* __alias__ "&#42;" ( +
factor: `Real[1]` +
): `<<_dvquantified_class,DvQuantified>>`
a|Product of this Amount and `_factor_`.

h|*1..1*
|*negative* __alias__ "-" (): `<<_dvquantified_class,DvQuantified>>`
a|Negated version of current object, such as used for representing a difference, e.g. a weight loss.

h|*1..1 +
(effected)*
|*less_than* __alias__ "<" ( +
other: `<<_dvquantified_class,DvQuantified>>[1]` +
): `Boolean` +
 +
__Post_result__: `Result = magnitude < other.magnitude`
a|True if this object is less than `_other_`. Based on comparison of `_magnitude_`.

h|*1..1 +
(effected)*
|*is_equal* ( +
other +
): `Boolean`
a|Return True if this `DV_QUANTIFIED` is considered equal to `_other_`.
|===
