=== Reference_range Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*Reference_range<T>*

h|*Description*
2+a|Defines a named range to be associated with any `DV_ORDERED` datum. Each such range is particular to the patient and context, e.g. sex, age, and any other factor which affects ranges. May be used to represent normal, therapeutic, dangerous, critical etc ranges.

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*meaning*: `link:/releases/BASE/{base_release}/foundation_types.html#_terminology_term_class[Terminology_term^]`
a|Term whose value indicates the meaning of this range, e.g.  normal,  critical,  therapeutic  etc.

h|*1..1*
|*range*: `Interval<<<_dv_quantified_class,Dv_quantified>>>`
a|The data range for this meaning, e.g. critical  etc.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*is_in_range* ( +
v: `<<_dv_ordered_class,Dv_ordered>>[1]` +
): `link:/releases/BASE/{base_release}/foundation_types.html#_boolean_class[Boolean^]`
a|Indicates if the value  `_v_` is inside the range.

h|*Invariants*
2+a|__Range_is_simple__: `(range.lower_unbounded or else range.lower.is_simple) and (range.upper_unbounded or else range.upper.is_simple)`
|===
