=== Assertion Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*Assertion*

h|*Description*
2+a|Entry type for assertions. Used for all kinds of statements which evaluate other information, such as interpretations of observations, diagnoses, differential diagnoses, hypotheses, risk assessments, goals and plans.

Should not be used for actionable statements such as medication orders - these are represented using the `Order` type.

GRAPHITE: Corresponds to many/most? CEMs for Dx and other assessments, e.g. 'elevated heart rate'. Assertions state what category the subject is in, rather than reporting specific characteristics and values.

h|*Inherit*
2+|`<<_care_entry_class,Care_entry>>`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*data*: `link:/releases/GCM/{gcm_release}/data_structures.html#_cluster_class[Cluster^]`
a|The data of this evaluation, in the form of a spatial data structure.

h|*0..1*
|*certainty*: `link:/releases/BASE/{base_release}/foundation_types.html#_terminology_code_class[Terminology_code^]`
a|
|===
