=== DvQuantity Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*DvQuantity*

h|*Description*
2+a|Quantitified type representing  scientific  quantities, i.e. quantities expressed as a magnitude and units. Units are expressed in the UCUM syntax (http://unitsofmeasure.org/ucum.html[Unified Code for Units of Measure (UCUM)], by Gunther Schadow and Clement J. McDonald of The Regenstrief Institute)  (case-sensitive form) by default, or another system if `_units_system_` is set.

Can also be used for time durations, where it is more convenient to treat these as simply a number of seconds rather than days, months, years (in the latter case, `DV_DURATION` may be used).

h|*Inherit*
2+|`<<_dvquantified_class,DvQuantified>>`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*unit_code*: `String`
a|Quantity units, expressed as a code or syntax string from either UCUM (the default) or the units system specified in `_unit_system_`, when set.

In either case, the value is the code or syntax - normally formed of standard ASCII - which is in principal not the same as the display string, although in simple cases such as 'm' (for meters) it will be.

If the `_units_display_` field is set, this may be used for display. If not, the implementations must effect the resolution of the `_unit_` value to a display form locally, e.g. by lookup of reference tables, request to a terminology service etc.

Example values from UCUM: "kg/m^2", “mm[Hg]", "ms-1", "km/h".

h|*0..1*
|*unit_system*: `String`
a|Optional field used to specify a units system from which codes in `_unit_` are defined. Value is a URI identifying a terminology containing units concepts from the  (https://www.hl7.org/fhir/terminologies-systems.html[HL7 FHIR terminologies list]).

If not set, the UCUM standard (case-sensitive codes) is assumed as the unit system.

h|*0..1*
|*unit_display*: `String`
a|Optional field containing the displayable form of the `_unit_` field, e.g. `'°C'`.

If not set, the application environment needs to determine the displayable form.

NOTE: The display name may be language-dependent for various older and non-systematic units. For this reason, it is not recommended to add unit display names to archetypes, only to templates (for localisation purposes).

h|*1..1 +
(redefined)*
|*magnitude*: `Real`
a|
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1 +
(redefined)*
|*add* __alias__ "+" ( +
other: `<<_dvquantity_class,DvQuantity>>[1]` +
): `<<_dvquantity_class,DvQuantity>>`
a|Sum of this `DV_QUANTITY` and `_other_`.

h|*1..1 +
(redefined)*
|*subtract* __alias__ "-" ( +
other: `<<_dvquantity_class,DvQuantity>>[1]` +
): `<<_dvquantity_class,DvQuantity>>`
a|Difference of this `DV_QUANTITY` and `_other_`.

h|*1..1 +
(redefined)*
|*multiply* __alias__ "&#42;" ( +
factor: `Real[1]` +
): `<<_dvquantity_class,DvQuantity>>`
a|Product of this `DV_QUANTITY` and `_factor_`.

h|*1..1 +
(effected)*
|*less_than* __alias__ "<" ( +
other: `<<_dvquantity_class,DvQuantity>>[1]` +
): `Boolean` +
 +
__Post_result__: `Result = magnitude < other.magnitude`
a|True if this Quantity object is less than `_other_`, based on comparison of `_magnitude_`. Only valid if `_is_strictly_comparable_to()_` is True.

h|*1..1 +
(effected)*
|*is_strictly_comparable_to* ( +
other: `<<_dvordered_class,DvOrdered>>[1]` +
): `Boolean`
a|True if this quantity and `_other_` have the same `_units_` and also `_units_system_` if it exists.
|===
