=== Dv_count Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*Dv_count*

h|*Description*
2+a|Countable quantities. Used for countable types such as pregnancies and steps (taken by a physiotherapy patient), number of cigarettes smoked in a day.

Misuse: Not to be used for amounts of physical entities (which all have units).

h|*Inherit*
2+|`<<_dv_quantified_class,Dv_quantified>>`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1 +
(redefined)*
|*magnitude*: `link:/releases/BASE/{base_release}/foundation_types.html#_integer64_class[Integer64^]`
a|
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1 +
(redefined)*
|*add* __alias__ "+" ( +
other: `<<_dv_count_class,Dv_count>>[1]` +
): `<<_dv_count_class,Dv_count>>`
a|Sum of this `DV_COUNT` and `_other_`.

h|*1..1 +
(redefined)*
|*subtract* __alias__ "-" ( +
other: `<<_dv_count_class,Dv_count>>[1]` +
): `<<_dv_count_class,Dv_count>>`
a|Difference of this `DV_COUNT` and `_other_`.

h|*1..1 +
(redefined)*
|*multiply* __alias__ "&#42;" ( +
factor: `link:/releases/BASE/{base_release}/foundation_types.html#_real_class[Real^][1]` +
): `<<_dv_count_class,Dv_count>>`
a|Product of this `DV_COUNT` and `_factor_`.

h|*1..1 +
(effected)*
|*less_than* __alias__ "<" ( +
other: `<<_dv_count_class,Dv_count>>[1]` +
): `link:/releases/BASE/{base_release}/foundation_types.html#_boolean_class[Boolean^]` +
 +
__Post_result__: `Result = magnitude < other.magnitude`
a|True if this Quantified object is less than `_other_`, based on comparison of `_magnitude_`.

h|*1..1 +
(effected)*
|*is_strictly_comparable_to* ( +
other: `<<_dv_ordered_class,Dv_ordered>>[1]` +
): `link:/releases/BASE/{base_release}/foundation_types.html#_boolean_class[Boolean^]`
a|Return True.
|===
