=== Observation Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*Observation*

h|*Description*
2+a|Observation consisting of one time-point, and optional patient state.

h|*Inherit*
2+|`<<_care_act_entry_class,Care_act_entry>>`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*observation_time*: `link:/releases/BASE/{base_release}/foundation_types.html#_date_time_class[Date_time^]`
a|Time of original observation. For any observations based on specimens taken from the patient (tissue, excreta etc), this is the time at which the specimen was taken.

h|*0..1*
|*result_time*: `link:/releases/BASE/{base_release}/foundation_types.html#_date_time_class[Date_time^]`
a|Time at which result was generated. For most observations other than laboratory, the result time is the same as the observation time, for instruments and manual processes where that are effectively instant.

If not populated, value is assumed to be the same as `_observation_time_`.

h|*0..1*
|*data*: `List<link:/releases/GCM/{gcm_release}/data_structures.html#_item_class[Item^]>`
a|Result.

h|*0..1*
|*state*: `List<link:/releases/GCM/{gcm_release}/data_structures.html#_item_class[Item^]>`
a|Patient state at effective (clinically relevant) time.
|===
