=== DvMeasured Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*DvMeasured<V>*

h|*Description*
2+a|

h|*Inherit*
2+|`<<_dvordered_class,DvOrdered>>`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*0..1*
|*accuracy*: `Any`
a|Accuracy of measurement. A value of zero means no accuracy recorded.

h|*0..1*
|*accuracy_is_percent*: `Boolean`
a|If `True`, indicates that when this object was created, `_accuracy_` was recorded as a percent value; if `False`, as an absolute quantity value.

h|*0..1*
|*value_status*: `ComparisonOperator`
a|Optional status of magnitude with respect to real-world value:

* `"="`   : magnitude is a point value
* `"<"`   : value is < magnitude
* `">"`   : value is > magnitude
* `"\<="` : value is \<= magnitude
* `">="` : value is >= magnitude

If not present, assumed meaning is  `"="` .

h|*1..1*
|*value*: `V`
a|

h|*0..1*
|*normal_range*: `Interval<<<_dvquantified_class,DvQuantified>>>`
a|Optional normal range.

h|*0..1*
|*precision*: `Integer`
a|Precision to which the value of the quantity is expressed, in terms of number of decimal places. The value 0 implies an integral quantity.
The value -1 implies no limit, i.e. any number of decimal places.

h|*0..1*
|*other_reference_ranges*: `List<<<_referencerange_class,ReferenceRange>>>`
a|Optional tagged other reference ranges for this value in its particular measurement context.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*valid_magnitude_status* (): `Boolean` +
 +
__Post__: `Result = s in {"=", "<", ">", "\<=", ">=", "~"}`
a|Test whether a string value is one of the valid values for the magnitude_status attribute.

h|*Invariants*
2+a|__Accuracy_is_percent_validity__: `accuracy = 0 implies not accuracy_is_percent`

h|
2+a|__Accuracy_validity__: `accuracy_is_percent implies valid_percentage (accuracy)`
|===
