=== Assertion Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*Assertion*

h|*Description*
2+a|Entry type for an assertion, i.e. a truth claim about the subject. Used for  diagnoses, differential diagnoses, hypotheses, risk assessments, goals and plans.

GRAPHITE: Corresponds to many/most? CEMs for Dx and other assessments, e.g. 'elevated heart rate'. Assertions state what category the subject is in, rather than reporting specific characteristics and values.

h|*Inherit*
2+|`<<_care_entry_class,Care_entry>>`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*data*: `link:/releases/GCM/{gcm_release}/data_structures.html#_cluster_class[Cluster^]`
a|The data of this evaluation, in the form of a spatial data structure.

h|*0..1*
|*certainty*: `link:/releases/BASE/{base_release}/foundation_types.html#_terminology_code_class[Terminology_code^]`
a|

h|*1..1*
|*time*: `link:/releases/BASE/{base_release}/foundation_types.html#_date_time_class[Date_time^]`
a|Time at which assertion, e.g. diagnosis was made. This is usually 'now' but may report a historical diagnosis or other assessment.

TODO: do we need other meta-data for historical assertions?
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*effective_time* (): `link:/releases/BASE/{base_release}/foundation_types.html#_interval_class[Interval^]<link:/releases/BASE/{base_release}/foundation_types.html#_date_time_class[Date_time^]>`
a|Result = `_time_`.
|===
