=== Order_details Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*Order_details*

h|*Description*
2+a|Used to record details of the Instruction causing an Action.

h|*Inherit*
2+|`link:/releases/BASE/{base_release}/base_types.html#_locatable_class[Locatable^]`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*order_ref*: `link:/releases/BASE/{base_release}/base_types.html#_locatable_ref_class[Locatable_ref^]`
a|Reference to causing Instruction.

h|*1..1*
|*activity_id*: `link:/releases/BASE/{base_release}/foundation_types.html#_string_class[String^]`
a|Identifier of Activity within Instruction, in the form of its archetype path.

h|*0..1*
|*wf_details*: `link:/releases/GCM/{gcm_release}/data_structures.html#_cluster_class[Cluster^]`
a|Various workflow engine state details, potentially including such things as:

* condition that fired to cause this Action to be done (with actual variables substituted);
* list of notifications which actually occurred (with all variables substituted);
* other workflow engine state.

This specification does not currently define the actual structure or semantics of this field.

TODO: probably remove.

h|*Invariants*
2+a|__Activity_path_valid__: `not activity_id.is_empty`
|===
