=== Observation Class

[cols="^1,3,5"]
|===
h|*Class*
2+^h|*Observation*

h|*Description*
2+a|Entry subtype for all clinical data in the past or present, i.e. which (by the time it is recorded) has already occurred. `Observation` data is expressed using the class `HISTORY<T>`, which guarantees that it is situated in time. `Observation` is used for all notionally objective (i.e. measured in some way) observations of phenomena, and patient-reported phenomena, e.g. pain.

Not to be used for recording opinion or future statements of any kind, including iinstructions, intentions, plans etc.

GRAPHITE: Corresponds to many/most? Evaluation CEMs relating to observation activities e.g. auscultation etc.

h|*Inherit*
2+|`<<_care_act_entry_class,Care_act_entry>>`

h|*Attributes*
^h|*Signature*
^h|*Meaning*

h|*1..1*
|*data*: `link:/releases/GCM/{gcm_release}/data_structures.html#_history_class[History^]`
a|The data of this observation, in the form of a history of values which may be of any complexity.

h|*0..1*
|*state*: `link:/releases/GCM/{gcm_release}/data_structures.html#_history_class[History^]`
a|Optional recording of the state of subject of this observation during the observation process, in the form of a separate history of values which may be of any complexity. State may also be recorded within the History of the data attribute.
h|*Functions*
^h|*Signature*
^h|*Meaning*

h|*1..1 +
(effected)*
|*effective_time* (): `link:/releases/BASE/{base_release}/foundation_types.html#_interval_class[Interval^]<link:/releases/BASE/{base_release}/foundation_types.html#_date_time_class[Date_time^]>`
a|Result = `_data.origin_`.
|===
