= Entry and its Subtypes

The Entry model is defined by the `composition.content.entry package`, shown in the UML diagram below. The choice of subtypes of `Entry` is based on the ontology shown in <<CIR_ontology>> and its associated model. The names do not coincide exactly however, for a number of reasons. Firstly, the category names in the hierarchy were chosen based on a philosophical/scientific model of investigation, and reflecting linguistic norms for the meanings of the terms, whereas the class names used here reflect common health computing and clinical usage of these terms (i.e. names which will make sense to software developers in the health arena). Names in these two cultures do not always coincide. Additionally, for categories such as Opinion and Instruction, the subcategories shown in the ontology (e.g. Assessment, Goal and Plan) are too variable to safely be sub-typed in software, and are distinguished only at the archetype level. Only a single class for each of these ontological groups is used in the formal model. The use of different names and a slightly simplified mapping has not however prevented the faithful implementation of the semantics of the model. The model classes are described in the following subsections.

[.text-center]
.gcm.entry package
image::{uml_diagrams_uri}/GCM-entry-taxonomy.svg[id=entry_taxonomy, align="center"]

== The Entry class

All Entries have a number of attributes in common. The language and encoding attributes indicate how all text data within the Entry are to be interpreted linguistically and at the character set level. Normally, the language will be the same throughout the entire Entry (if not Composition), but in cases where it is not, the optional language attribute of `Dv_text` can be used to override the value in the enclosing `Entry` (or other enclosing structure, if a `Dv_text` is being used in some other context). Character encoding can be overridden in the same fashion by the encoding attribute within `Dv_text`.

The other attributes common to all Entry subtypes are as follows:

* `_subject_`: this attribute records the subject of the Entry as an instance of a subtype of `Party_proxy`. When this is the record subject, (i.e. the patient), the value is an instance of `Party_self`. Otherwise it is typically a family member, sexual partner, or other acquaintance of the record subject. It could also be an organ donor. The latter is expressed in the form of a `Party_identified` or `Related_party` instance, which describes the kind of relationship, and optionally, identifies the demographic entity.
* `_subject_is_self_`: convenience function returning True when the Entry is about the subject of the record.
* `_provider_`: the agent who provided the information. This is usually the patient or the clinician, but may be someone else, or a software application or device. If participation details of the provider (e.g. mode of communication) need to be recorded, the details should be recorded once in the `Event_context._participations_`. The provider attribute is optional, since it is often implicit in the information that was recorded.
* `_other_participations_`: other participations which existed for this Entry, e.g. a nurse who administered a drug in an `Order`; only required in cases where participants other than the subject of the information and the provider of the information need to be recorded.

Note that the term 'provider' as used here should not be confused with the more specific healthcare term used in many english-speaking countries meaning 'health care provider', which is usually understood to be a physician or healthcare delivery enterprise such as a hospital. In the model here, it simply means 'provider of information' in the context of an Entry. The information provider is optional, and in many cases will not be recorded, since it will be obvious from the `_composer_` and `_other_participations_` of the enclosing Composition. In many cases, it is not sensible to record a provider, e.g. in the most mundane case where a GP asks "where does it hurt" and the patient says "here" - in such cases, it can only be considered mutual. It is expected to be used only when the composer of the Composition really needs to specify the origin of specific statements, such as in the following circumstances:

* the information provider is specifically accountable for the Entry data (it is their opinion, their decision, they carried out the test etc.) - they might also need to attest it;
* the information provider is an authoritative source, or has provided information from a unique perspective (e.g. the view of a spouse/ carer on the patient's functional health status or mental state);
* the information provider's view might not reflect the consensus (e.g. a patient opinion not held by the composer, a difference between father and mother on a description of a child's sleeping pattern);
* the information provider is not one of the Composition-level participants (e.g. an outside information provider such as someone telephoned during the encounter to provide a lab result, or an automated measurement device, or a decision support software component).

== Care_entry

A basic division occurs between clinical and non-clinical information. The `Care_entry` class is an abstract precursor of classes that express information of any clinical activity in the care process around the patient, while `Admin_entry` is used to capture administrative information. The division may occasionally seem ambiguous at a theoretical level, but at a practical level, it is almost always clear. Administrative information has the following characteristics:

* it is created by non-clinical staff, or clinical staff acting in an administrative capacity (e.g. a nurse or doctor who has to fill out an admission form in A&E);
* it expresses details to do with coordinating the clinical process, by recording e.g. admission information (enables clinical staff to know who is in the hospital and where they can be found), appointments (ensuring patient and physician get together at an agreed time and place), discharge/dismissal (allowing clinical staff to know that a patient has been sent home healthy, or transferred to another institution), billing and insurance information (where such information is required in the EHR; it may well be in its own system);
* removing administrative information from the EHR would not compromise its clinical integrity, it would simply mean that carers and patients would no longer know when and where they were supposed to meet, or when the patient has entered or left a health care facility.

Conversely, every instance of a `Care_entry` subtype is clinically significant, even if it also carries information which might be of interest to other health management functions billing (e.g. {who_icd}[ICD10^] coded diagnoses), practice management (e.g. date, time and place in an order for day surgery). The `Care_entry` type includes two attributes particular to all clinical entries, namely `_protocol_` and `_guideline_id_`.

These attributes allow the 'how' and 'why' aspects of any clinical recording to be expressed. Protocol is often recorded for Observations, e.g. staining method in microscopy, and Instructions, e.g. Bruce protocol for ECG test.

== Care_act_entry

TBD

== Class Descriptions

include::{uml_export_dir}/classes/{pkg}entry.adoc[]

include::{uml_export_dir}/classes/{pkg}authorization.adoc[]

include::{uml_export_dir}/classes/{pkg}care_entry.adoc[]

include::{uml_export_dir}/classes/{pkg}care_act_entry.adoc[]

include::{uml_export_dir}/classes/{pkg}admin_entry.adoc[]
