= Miscellaneous Types

TBD

[.text-center]
.gcm.data_types package
image::{uml_diagrams_uri}/GCM-data_types.svg[id=data_types, align="center"]

== Boolean Values

One of the most basic types of data is boolean data.

TBD

=== Class Descriptions

include::{uml_export_dir}/classes/{pkg}dv_boolean.adoc[leveloffset=+1]

== Real World Identifiers

=== Requirements

Real world entities (RWEs) such as people, car engines, invoices, and appointments may all be assigned identifiers. Although many of these are designed to be unique within a jurisdiction or issuing space, they are often not, due to data entry errors, bad design (ids which are too small or incorporate some non-unique characteristic of the identified entities), bad process (e.g. non-synchronised id issuing points); identity theft (e.g. via theft of documents of proof or hacking). In general, while some real world identifiers (RWIs) are 'nearly unique', none can be guaranteed so. Therefore, from a strict computational point of view, RWIs are not treated as reliable identifiers, but as attributes of their owning objects, in the same ways as names and addresses for example.

Examples of RWE identifiers which are intended to be unique within the space of the issuing authority or organisation include:

* driver's licence id
* social security number
* passport number
* prescription id

The defining logical characteristic of RWE ids is that they continue to identify the entities in question, regardless of how they change in time; for example a social security number does not change when someone changes their hair colour or even their gender (both of which attributes may be recorded in the database). In general it should be the case that if two RWE ids are equal, they refer to the same RWE.

At a practical level, RWE identifiers differ from information entity (IE) identifiers in that the former are generally not assigned by the computing infrastructure that uses them - that is to say, in the production computing system, such identifiers are no different from other characteristics of the entity, such as names or addresses.

=== Semantics

The model defined here in the `DV_IDENTIFIER` class allows the recording of three things as part of identifying an item of interest:

* the identifier given to the item of interest (mandatory).
* the issuing authority of the kind of id used (e.g. it might be the federal department of health) (optional);
* the assigner of the id to the item being identified. This is usually the organisation which created the item being identified (optional);

In addition, a type of item being identified can also be recorded, such as 'driver's licence' or 'Medicare card'. All fields are text fields, rather than coded, as no definitive vocabularies are available. However, some useful sources of terms exists, such as https://www.hl7.org/fhir/v2/0203/index.html[HL7v2 Table 0203^] for the `type` field. If using the latter, it is recommended to use the 'description', not the code.

Only the `identifier` field is mandatory to allow for use cases in which the other fields cannot be populated. However it is strongly recommended to populate the `type` and `issuer` fields where possible. In many cases the `issuer` and `assigner` have the same value, however two fields allow for the situation in which a central issuer provides blocks of identifiers (typically on some kind of form or other paperwork) to other organisations who then assign them to individuals, as is often done with prescription identifiers.

See the {openehr_base_types}#_identification_package[Support Base Types specification^] for a further discussion of RWEs and IEs, and the definition of IEs in openEHR.

=== Class Descriptions

include::{uml_export_dir}/classes/{pkg}dv_identifier.adoc[leveloffset=+1]

== Timing

TBD

=== Class Descriptions

include::{uml_export_dir}/classes/{pkg}dv_timing.adoc[leveloffset=+1]
